=begin
#OmniCore Model and State Management API

#This is an OmniCore Model and State Management server.

The version of the OpenAPI document: 1.8.7
Contact: omnicoresupport@korewireless.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OmniCoreClient::ListSinks
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OmniCoreClient::ListSinks do
  let(:instance) { OmniCoreClient::ListSinks.new }

  describe 'test an instance of ListSinks' do
    it 'should create an instance of ListSinks' do
      expect(instance).to be_instance_of(OmniCoreClient::ListSinks)
    end
  end
  describe 'test attribute "sinks"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
