=begin
#OmniCore Model and State Management API

#This is an OmniCore Model and State Management server.

The version of the OpenAPI document: 1.8.1
Contact: omnicoresupport@korewireless.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::LogLevel
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::LogLevel do
  let(:instance) { OpenapiClient::LogLevel.new }

  describe 'test an instance of LogLevel' do
    it 'should create an instance of LogLevel' do
      expect(instance).to be_instance_of(OpenapiClient::LogLevel)
    end
  end
end
