=begin
#OmniCore Model and State Management API

#This is an OmniCore Model and State Management server.

The version of the OpenAPI document: 1.8.1
Contact: omnicoresupport@korewireless.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0-SNAPSHOT

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/bind_request'
require 'openapi_client/models/bind_request_ids_gateway'
require 'openapi_client/models/block_communication_body'
require 'openapi_client/models/config'
require 'openapi_client/models/custom_onboard'
require 'openapi_client/models/device'
require 'openapi_client/models/device_command'
require 'openapi_client/models/device_config'
require 'openapi_client/models/device_configuration'
require 'openapi_client/models/device_credential'
require 'openapi_client/models/device_registry'
require 'openapi_client/models/device_state'
require 'openapi_client/models/error_frame'
require 'openapi_client/models/error_status'
require 'openapi_client/models/event_notification_config'
require 'openapi_client/models/gateway_config'
require 'openapi_client/models/generic_error_response'
require 'openapi_client/models/http_config'
require 'openapi_client/models/info'
require 'openapi_client/models/list_device_config_versions_response'
require 'openapi_client/models/list_device_registries'
require 'openapi_client/models/list_device_states_response'
require 'openapi_client/models/list_devices_response'
require 'openapi_client/models/list_sinks'
require 'openapi_client/models/log_level'
require 'openapi_client/models/metrics'
require 'openapi_client/models/metrics_details'
require 'openapi_client/models/mqtt_config'
require 'openapi_client/models/notification_config'
require 'openapi_client/models/policy'
require 'openapi_client/models/public_key_certificate'
require 'openapi_client/models/public_key_credential'
require 'openapi_client/models/registry_credential'
require 'openapi_client/models/sink'
require 'openapi_client/models/x509_certificate_details'

# APIs
require 'openapi_client/api/device_api'
require 'openapi_client/api/metrics_api'
require 'openapi_client/api/registry_api'
require 'openapi_client/api/sink_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
